### ISSUE TITLE
An error was reported when I installed pstools

### ISSUE THREAD

**Issue by Ahahaha3** [shilpagarg/pstools#1]
dear author: i've installed g++ and zlib, but an error was reported when I installed pstools:

/home/miniconda3/bin/x86_64-conda-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/miniconda3/include  -c -o hic_switch_error.o hic_switch_error.cpp
hic_switch_error.cpp: In function 'void get_switch_error(pldat_t*, bseq_file_t*, bseq_file_t*, std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >)':
hic_switch_error.cpp:538:31: error: unable to find string literal operator 'operator""PRIu64' with 'const char [13]', 'long unsigned int' arguments
     printf("Switch at %"PRIu64"\n", condensed_counting[p].first);
                               ^~~~
hic_switch_error.cpp:541:33: error: unable to find string literal operator 'operator""PRIu64' with 'const char [15]', 'long unsigned int' arguments
     printf("Unswitch at %"PRIu64"\n", condensed_counting[p].first);
                                 ^~~~
hic_switch_error.cpp:564:31: error: unable to find string literal operator 'operator""PRIu64' with 'const char [15]', 'long unsigned int' arguments
   printf("Unswitched: %"PRIu64"\n", total_vars - hamming_distance);
                               ^~~~
hic_switch_error.cpp:565:29: error: unable to find string literal operator 'operator""PRIu64' with 'const char [13]', 'long unsigned int' arguments
   printf("Switched: %"PRIu64"\n", hamming_distance);
                             ^~~~
hic_switch_error.cpp:567:40: error: unable to find string literal operator 'operator""PRIu64' with 'const char [38]', 'long unsigned int' arguments
   printf("Switch error number: %"PRIu64", rate: %.4f%%\n", switch_error_count, ((double) switch_error_count)/ (condensed_counting.size()-1) * 100);
                                        ^~~~~~~~~~~~~~~~~~
hic_switch_error.cpp:595:40: error: unable to find string literal operator 'operator""PRIu64' with 'const char [25]', 'long unsigned int' arguments
  printf("Overall total length: %"PRIu64"\n",overall_total_length);
                                        ^~~~
hic_switch_error.cpp:596:40: error: unable to find string literal operator 'operator""PRIu64' with 'const char [24]', 'long unsigned int' arguments
  printf("\nOverall Unswitched: %"PRIu64"\n", overall_total_vars - overall_hamming_distance);
                                        ^~~~
hic_switch_error.cpp:597:36: error: unable to find string literal operator 'operator""PRIu64' with 'const char [21]', 'long unsigned int' arguments
  printf("Overall Switched: %"PRIu64"\n", overall_hamming_distance);
                                    ^~~~
hic_switch_error.cpp:599:47: error: unable to find string literal operator 'operator""PRIu64' with 'const char [46]', 'long unsigned int' arguments
  printf("Overall Switch error number: %"PRIu64", rate: %.4f%%\n", overall_switch_error_count, ((double) overall_switch_error_count)/ overall_potiential_switch_count * 100);
                                               ^~~~~~~~~~~~~~~~~~
make: *** [<builtin>: hic_switch_error.o] Error 1

**Comment by shilpagarg** [comment]
Please see https://github.com/shilpagarg/DipAsm/issues/16.
