### ISSUE TITLE
making error

### ISSUE THREAD

**Issue by zhongmicai** [shilpagarg/pstools#2]
i got a error during make process, the error was as follow: hic_mapping.cpp: 320:11 error:  'idx' does not name a type for (auto idx: counts) . i test it on several linux platform with different g++ version

**Comment by shilpagarg** [comment]
Please use ```conda install libgcc=5.2.0```, or alternatively, please see https://github.com/shilpagarg/DipAsm/issues/16.

**Comment by chunlinxiao** [comment]
got same error - not sure how to proceed after "conda install libgcc=5.2.0". 

Also the link for pstools binary seems not working (https://pstools.s3.us-east-2.amazonaws.com/pstools_1)
