### ISSUE TITLE
pred_haplotypes.fa

### ISSUE THREAD

**Issue by zhoudreames** [shilpagarg/pstools#3]
I see the output file_pred_haplotypes.fa,there are two haplotype header.if can i directly split >utg*hap1 or >utg*hap2 into hap1.fa or hap2.fa ?
![image](https://user-images.githubusercontent.com/54714639/106721138-41551580-663f-11eb-8de2-27518472d263.png)

**Comment by shilpagarg** [comment]
Please see https://github.com/shilpagarg/DipAsm/issues/20.

**Comment by zhoudreames** [comment]
> Please see [shilpagarg/DipAsm#20](https://github.com/shilpagarg/DipAsm/issues/20).

thanks! how to use the pstools_1 ？before i used the code show blow
/home/goldenpigs/software/pstools-main/pstools  hic_mapping -t50 -o v130.out Male.r_utg.fa Male_Hi-C_R1.fq.gz  Male_Hi-C_R2.fq.gz
/home/goldenpigs/software/pstools-main/pstools resolve_haplotypes -t50 -i true v130.out  Male.r_utg.gfa ./
